---
abstract: 'enumrated scalar values'
author:
  - 'Robert Rothenberg C<rrwo@cpan.org>.'
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Readonly-Enum
no_index:
  directory:
    - inc
    - t
requires:
  Scalar::Readonly: 0
  perl: 5.01
  version: 0.77
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/robrwo/Readonly-Enum.git
version: 0.001001
